name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./de.robinscloud.admin-ui
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
